### ISSUE TITLE
Simple Figma Design

### ISSUE THREAD

**Issue by lcaohoanq** [SWP391-613/Koi-Auction-FE#9]

**Comment by DuongNManh** [comment]
figma team: [https://www.figma.com/team_invite/redeem/WtE3E8h8DGQ0BAieKJ4oYa](https://www.figma.com/team_invite/redeem/WtE3E8h8DGQ0BAieKJ4oYa?fbclid=IwZXh0bgNhZW0CMTAAAR1DaNiGsasQqhD6UYx1i3DZapsO-1E0Py-HPE5v-tS4o8bVRmE1RNp0e78_aem_RmgHj6RKnHXX7fJfWziFFw)

**Comment by lcaohoanq** [comment]
cc: @DuongNManh @dduongCongSon  
Divide this to smaller, each page with each issue
